### PR TITLE
New feature: Install module from a user-selectable zip file

### PR DESCRIPTION
**Pull request by tuomas2**
This PR adds functionality to select from main menu "Install Documents from a Zip file". This feature is intended to make it much more convenient for users to install propietary modules that cannot be distributed through public repositories.

1. User can give a file through ACTION_GET_CONTENT intent. 
2. Given file is first checked that it contains a configuration file in mods.d and modules directory, and then extracted and registered. 
3. After install is finished, toast message informs the user of the result.

### CODE REVIEW

**Comment by ildar** [comment]
Does it install modules into /sdcard/jSword folder? Or the usual
Android/data/... ?

**Comment by tuomas2** [comment]
It installs module in Android/data/...

**Comment by mjdenham** [comment]
Thanks for doing this.  I have just been trying it out and I think some people are going to like it a lot.  I plan to do a test build with it included shortly.

**Comment by mjdenham** [comment]
I have kept this on a separate branch for now but plan to move them over to development later.

**Comment by mjdenham** [comment]
Hi Tuomas, do you think yesterday's changes will solve BV's problem?  Also we should allow reload of modules so a module developer who continuously enhances a module can update easily but there may possibly be jsword issues replacing modules.
Martin

**Comment by tuomas2** [comment]
Sorry, I was not following the mailing list. Now I should get all messages from there. Yes, it seems that BV has faced just the same problem, which I fixed.

**Comment by mjdenham** [comment]
Hi Tuomas,

I notice that you prevent re-installation of modules that already exist.  This might be a nice feature for module developers who wish to try a newer version.  Was there any particular reason you disabled this - like did problems occur when re-installing over an existing module?

Cheers
Martin

**Comment by tuomas2** [comment]
I have uninstalled modules every time before re-installing. The reason that I implemented it this way was that I wanted to make sure that there may not happen unintentional overwriting of files that belong to other modules (if module is bad/broken). Re-installation feature would require some extra checking -- probably best approach would be to first perform uninstall of the module and then install as normally. 

Thanks for pushing this forward ;)

**Comment by mjdenham** [comment]
I can't work out how to change the logic to allow documents to be overwritten.  The flow is a bit different to what I normally use.  If I could work it out then there is still the issue of creating a Book to be uninstalled.
The code to remove an existing module/document/book can be gleaned from DownloadManager:
Books.installed().removeBook(book);

If you have any ideas on the above then you are welcome to try.  If not, the functionality is still very useful even without allowing overwrite.

**Comment by tuomas2** [comment]
Most simple approach would be to inform user of the files that would be overwritten and by his permission proceed (with "if unsure, say No"). What do you think? 

It's okay for me to leave it as is for now also. Those genbook issues that I have reported have bigger priority for me at the moment (I'm might be contributing to them in the (near) future).

**Comment by mjdenham** [comment]
Did you consider using the zip expansion code in JSword - IOUtil.unpackZip()?

**Comment by tuomas2** [comment]
unpackZip uses ZipFile instead of ZipInputStream. ZipFile would have allowed somewhat more convenient handling of zipfile (i.e. for example going through first filenames without compressing whole file, for overwrite checking), but I was not able to get it working with InputStreams (Zip file might not be stored at all in file storage when it comes from GET_ACTION_CONTENT / PICK_FILE intent). Moreover, there are no overwrite checking in unpackZip, so that should have been implemented there.

**Comment by mjdenham** [comment]
It would be good to make Zip file installation accessible as an alternative to Download during initial startup.  This would help in a lot of missionary situations.  I have had this sort of request at various times and again just yesterday.

**Pull request merged**
