### PR TITLE
I edited some strings in the Swedish Translation

### PR DESCRIPTION
**Pull request by 1jr**
There were some annoying errors in the Swedish translation. I fixed the worst ones.

### CODE REVIEW

**Comment by mjdenham** [comment]
Hi, thanks for that.  The original Swedish translator dropped out some time ago, so I believe there are a lot of untranslated Swedish strings.  Would you be happy to become the Swedish translator for And Bible.  We use transifex.com for translations which makes it fairly easy to translate strings.

If you are willing then the first step would be to register on www.transifex.com by pressing the 'Try it for free' button.  Then tell me your username so I can link you to the Swedish translation.

Thanks
Martin

**Comment by 1jr** [comment]
Hi Martin!

I'd love to help with the Swedish translation! Oh, I didn't know you used Transifex! I already have an account there. My username is 1jr

Jesper

Martin <notifications@github.com> skrev: (29 september 2015 00:06:56 CEST)

**Comment by mjdenham** [comment]
Hi Jesper,

I have manually applied your updates to the And Bible Swedish localisation in Transifex as a starting point and assigned you as the translation coordinator.

I will close this merge request now.

Thanks
Martin

**Comment by 1jr** [comment]
Sounds great!

I'll continue from there! If all goes well I will get some more strings done before the end of this week.

Jesper

**Pull request closed without merging**
